# Equations and Functions

## Solving Equations

In general we can solve different types of equations to get an exact solution. The solution may be an integer, a fraction, or it may be an expression. Using Maple we can do the same thing using the `solve` command and obtain an exact solutions for equations and inequalities. 

## Equations with multiple unknowns

You can use the solve command to solve equations having several variables. However you have to specify, for which variable that the equation to be solved.


## Functions
Let \(f\) be a function of \(x\). We denote it as \(f(x)\), but in Maple there is a different way to define such functions.

### Defining functions

### Function Operations and Compositions

### Composition of functions

## Trigonometry with Maple

<!-- sin, cos, ... - The Trigonometric functions\
sinh, cosh, ... - The Hyperbolic functions 
Calling Sequence-->

- The Trigonometric functions

\[
\begin{aligned}
 \sin(x) && \cos(x) && \tan(x) \\
 \sec(x) && \csc(x) && \cot(x)
\end{aligned}
\]

- The Hyperbolic functions

\[
\begin{aligned}
 \sinh(x) && \cosh(x) && \tanh(x) \\
 \text{sech}(x) &&  \text{csch}(x) && \text{coth}(x) 
\end{aligned}
\]


## Inverse trigonometric functions

\[
\begin{aligned}
 &\arcsin(x)        && \arccos(x)  && \arctan(x)\\
 &\text{arcsec}(x)  && \text{arccsc}(x)  && \text{arccot}(x)\\
 &\text{arcsinh}(x) && \text{arccosh}(x) && \text{arctanh}(x)\\
 &\text{arcsech}(x) && \text{arccsch}(x) && \text{arccoth}(x)
\end{aligned}
\]


## Exercise

```{exercise}
Find the solutions of the following equations to 5 decimal places.

i. \(2x^3 + 3x + 1 = 0\)
ii. \(2x^3 + 3x + \frac{1}{4} = 0\)
iii. \(x^2 - 13x + 10 = 0\)
iv. \(-3x + \frac{1}{2}x^2 = 25\)
```

```{exercise}
Find the most accurate real solutions to the following equations.

i. \(x^4 - 2x^3 = 7\)
ii. \(\frac{7}{(x-3)^2} + \frac{5}{(x+5)}\)
```

```{exercise}
Express the following in the form of \(y =mx +c\) using the `solve` command.

i. \(3x + 4y = 2\)
ii. \(\frac{3y}{5} - 2x + 7 = 0\)
iii. \(\frac{x}{x-3} + \frac{y}{2x} = -3\)

Use the Maple help to find another way to do the above.\
(Hint: You have to `isolate` y in each equation.)
```

```{exercise}
Consider, \(f(x) = 2x -\frac{x}{3(x+1)}\)

i. Define \(f\) as a function: \(f(x) = 2x - \frac{x^3}{x+1}\)
ii. Evaluate \(f(-\frac{1}{2})\)
iii. Factor \(f(x)\)
iv. Simplify \(f(\frac{1}{t-1})\)
```
```{exercise}
Use Maple help to find out how to find `logarithms`. Then find the value of the following.

i. \(\log_{10} 100\)
ii. \(\ln 100\)
iii. \(\log_3 10\)
iv. \(2\log_3 81 + 5\log_8 256\)
```
```{exercise}
Find the value of the following trigonometric expressions for given \(x\).
  
i. \(\sin(\sec(x^2)) + 3x\cos^3(\frac{2x}{7})\), where \(x = 71^\circ\).
ii. \(\sec^{-1}(\tanh(x+5))\cos(\sec(2x) + \sin(2x))\), where \(x = 43^\circ\).
iii. \(\left(\cot^{-1}(x) + \sec^{-1}(\frac{x-3}{5})\right)^{\frac{1}{3}}\), where \(x = 71^circ\).
```

